version: '3'
services:
  auth:
    build: .
    ports:
      - 13338:13337
    working_dir: /home/ctf
    entrypoint: /etc/init.sh
    init: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
